name: octxy dianzan Everyday


on:
  schedule:
      - cron: "10 8 * * *"
      - cron: "20 12 * * *"
      - cron: "50 14 * * *"
      - cron: "20 15 * * *"
      - cron: "10 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # 使用 node:10
    - name: use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    # npm install
    - name: "运行 点赞"
      run: |
        node oct51Activity.js
