name: ly SignIn Everyday


on:
  gollum:
  schedule:
      - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # 使用 node:10
    - name: use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    # npm install
    - name: "运行 【绿源 】"
      run: |
        npm install
        node ly.js
