name: octxy SignIn Everyday


on:
  gollum:
  schedule:
      - cron: "0 11 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # 使用 node:10
    - name: use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    # npm install
    - name: "运行 【签到 和 茶叶签到等】"
      env:
        USERCODE1: ${{ secrets.USERCODE1 }}
        USERCODE2: ${{ secrets.USERCODE2 }}
      run: |
        npm install
        node oneByOneDay.js
        node yadea.js
        node jd_sign.js
